import type { Metadata } from "next";
import { Kanit, Poppins, Lato } from "next/font/google";
import "./globals.css";
import Header from "./components/header/Header";
import "@fortawesome/fontawesome-free/css/all.min.css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const kanit = Kanit({
  subsets:["latin"],
  weight: ["100","200","300","400","500","600"],
  variable:"--kanit-font"
})

const poppins = Poppins({
  subsets:["latin"],
  weight: ["100","200","300","400","500","600"],
  variable:"--poppins-font"
})

const lato = Lato({
  subsets:["latin"],
  weight: ["100","300","400","700","900"],
  variable:"--lato-font"
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" className={`${kanit.variable} ${poppins.variable} ${lato.variable}`}>
      <body>
        <Header/>
        {children}
      </body>
    </html>
  );
}
